Use logger instead of default_logger
default_logger cannot be assigned:

undefined method `defaul_logger=' for #<Rollbar::ConfiguredOptions:0x000000000379f5b0> (NoMethodError)